// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvarolppmfsljzeiivba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YXJvbHBwbWZzbGp6ZWlpdmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk4OTczODUsImV4cCI6MjA3NTQ3MzM4NX0.8ofNvvnCkrs1HYoCI_qu1KZyhIF1EVvW98CcPl31_sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});